/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export interface LeaderboardEntry {
    xp: bigint;
    streak: bigint;
    userId: UserId;
    name: string;
}
export type Time = bigint;
export interface BadgeView {
    id: bigint;
    icon: string;
    name: string;
    description: string;
    requirement: string;
}
export type XP = bigint;
export interface UserSummary {
    xp: bigint;
    streak: bigint;
    name: string;
    role: UserRole;
    email: string;
}
export interface UserProfileView {
    xp: bigint;
    streak: bigint;
    name: string;
    createdAt: Time;
    badges: Array<BadgeView>;
    role: UserRole;
    email: string;
    lastActive: Time;
}
export interface AchievementsResponse {
    allBadges: Array<BadgeView>;
    message: string;
    xpEarned: XP;
    newBadge: BadgeView;
}
export interface Badge {
    id: bigint;
    icon: string;
    name: string;
    description: string;
    requirement: string;
}
export enum UserRole {
    admin = "admin",
    user = "user"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminAssignRole(user: Principal, role: UserRole__1): Promise<void>;
    adminGetAllUsers(): Promise<Array<UserProfileView>>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    checkAndUpdateAchievements(userId: UserId, newXP: XP): Promise<AchievementsResponse>;
    getAchievements(): Promise<Array<Badge>>;
    getCallerUserProfile(): Promise<UserProfileView>;
    getCallerUserRole(): Promise<UserRole__1>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getUserProfile(user: UserId): Promise<UserProfileView>;
    getUserSummary(userId: Principal): Promise<UserSummary>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfileView): Promise<UserProfileView>;
}
import type { BadgeView as _BadgeView, Time as _Time, UserProfileView as _UserProfileView, UserRole as _UserRole, UserRole__1 as _UserRole__1, UserSummary as _UserSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminAssignRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAssignRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAssignRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminGetAllUsers(): Promise<Array<UserProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkAndUpdateAchievements(arg0: UserId, arg1: XP): Promise<AchievementsResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndUpdateAchievements(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndUpdateAchievements(arg0, arg1);
            return result;
        }
    }
    async getAchievements(): Promise<Array<Badge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfileView_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfileView_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfileView_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfileView_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSummary(arg0: Principal): Promise<UserSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSummary(arg0);
                return from_candid_UserSummary_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSummary(arg0);
            return from_candid_UserSummary_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileView): Promise<UserProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileView_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfileView_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileView_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfileView_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_UserProfileView_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileView): UserProfileView {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserSummary_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSummary): UserSummary {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    streak: bigint;
    name: string;
    role: _UserRole;
    email: string;
}): {
    xp: bigint;
    streak: bigint;
    name: string;
    role: UserRole;
    email: string;
} {
    return {
        xp: value.xp,
        streak: value.streak,
        name: value.name,
        role: from_candid_UserRole_n6(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    streak: bigint;
    name: string;
    createdAt: _Time;
    badges: Array<_BadgeView>;
    role: _UserRole;
    email: string;
    lastActive: _Time;
}): {
    xp: bigint;
    streak: bigint;
    name: string;
    createdAt: Time;
    badges: Array<BadgeView>;
    role: UserRole;
    email: string;
    lastActive: Time;
} {
    return {
        xp: value.xp,
        streak: value.streak,
        name: value.name,
        createdAt: value.createdAt,
        badges: value.badges,
        role: from_candid_UserRole_n6(_uploadFile, _downloadFile, value.role),
        email: value.email,
        lastActive: value.lastActive
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfileView>): Array<UserProfileView> {
    return value.map((x)=>from_candid_UserProfileView_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfileView_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileView): _UserProfileView {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    streak: bigint;
    name: string;
    createdAt: Time;
    badges: Array<BadgeView>;
    role: UserRole;
    email: string;
    lastActive: Time;
}): {
    xp: bigint;
    streak: bigint;
    name: string;
    createdAt: _Time;
    badges: Array<_BadgeView>;
    role: _UserRole;
    email: string;
    lastActive: _Time;
} {
    return {
        xp: value.xp,
        streak: value.streak,
        name: value.name,
        createdAt: value.createdAt,
        badges: value.badges,
        role: to_candid_UserRole_n14(_uploadFile, _downloadFile, value.role),
        email: value.email,
        lastActive: value.lastActive
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
