/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AchievementsResponse {
  'allBadges' : Array<BadgeView>,
  'message' : string,
  'xpEarned' : XP,
  'newBadge' : BadgeView,
}
export interface Badge {
  'id' : bigint,
  'icon' : string,
  'name' : string,
  'description' : string,
  'requirement' : string,
}
export interface BadgeView {
  'id' : bigint,
  'icon' : string,
  'name' : string,
  'description' : string,
  'requirement' : string,
}
export interface LeaderboardEntry {
  'xp' : bigint,
  'streak' : bigint,
  'userId' : UserId,
  'name' : string,
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfileView {
  'xp' : bigint,
  'streak' : bigint,
  'name' : string,
  'createdAt' : Time,
  'badges' : Array<BadgeView>,
  'role' : UserRole,
  'email' : string,
  'lastActive' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'xp' : bigint,
  'streak' : bigint,
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type XP = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminAssignRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'adminGetAllUsers' : ActorMethod<[], Array<UserProfileView>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'checkAndUpdateAchievements' : ActorMethod<
    [UserId, XP],
    AchievementsResponse
  >,
  'getAchievements' : ActorMethod<[], Array<Badge>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfileView>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getUserProfile' : ActorMethod<[UserId], UserProfileView>,
  'getUserSummary' : ActorMethod<[Principal], UserSummary>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileView], UserProfileView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];