/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BadgeView = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'requirement' : IDL.Text,
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserProfileView = IDL.Record({
  'xp' : IDL.Nat,
  'streak' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'badges' : IDL.Vec(BadgeView),
  'role' : UserRole,
  'email' : IDL.Text,
  'lastActive' : Time,
});
export const UserId = IDL.Principal;
export const XP = IDL.Nat;
export const AchievementsResponse = IDL.Record({
  'allBadges' : IDL.Vec(BadgeView),
  'message' : IDL.Text,
  'xpEarned' : XP,
  'newBadge' : BadgeView,
});
export const Badge = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'requirement' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'xp' : IDL.Nat,
  'streak' : IDL.Nat,
  'userId' : UserId,
  'name' : IDL.Text,
});
export const UserSummary = IDL.Record({
  'xp' : IDL.Nat,
  'streak' : IDL.Nat,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminAssignRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserProfileView)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'checkAndUpdateAchievements' : IDL.Func(
      [UserId, XP],
      [AchievementsResponse],
      [],
    ),
  'getAchievements' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfileView], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [UserProfileView], ['query']),
  'getUserSummary' : IDL.Func([IDL.Principal], [UserSummary], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfileView], [UserProfileView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BadgeView = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'requirement' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserProfileView = IDL.Record({
    'xp' : IDL.Nat,
    'streak' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'badges' : IDL.Vec(BadgeView),
    'role' : UserRole,
    'email' : IDL.Text,
    'lastActive' : Time,
  });
  const UserId = IDL.Principal;
  const XP = IDL.Nat;
  const AchievementsResponse = IDL.Record({
    'allBadges' : IDL.Vec(BadgeView),
    'message' : IDL.Text,
    'xpEarned' : XP,
    'newBadge' : BadgeView,
  });
  const Badge = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'requirement' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'xp' : IDL.Nat,
    'streak' : IDL.Nat,
    'userId' : UserId,
    'name' : IDL.Text,
  });
  const UserSummary = IDL.Record({
    'xp' : IDL.Nat,
    'streak' : IDL.Nat,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminAssignRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserProfileView)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'checkAndUpdateAchievements' : IDL.Func(
        [UserId, XP],
        [AchievementsResponse],
        [],
      ),
    'getAchievements' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfileView], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [UserProfileView], ['query']),
    'getUserSummary' : IDL.Func([IDL.Principal], [UserSummary], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [UserProfileView],
        [UserProfileView],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };